import { defineStore } from 'pinia';

import { createUserProfileServiceClient } from '#/generated/api/admin/service/v1';
import { makeUpdateMask, omit } from '#/utils/query';
import { requestClientRequestHandler } from '#/utils/request';

export const useUserProfileStore = defineStore('user-profile', () => {
  const userProfileService = createUserProfileServiceClient(
    requestClientRequestHandler,
  );

  /**
   * Get current user
   */
  async function getMe() {
    try {
      return await userProfileService.GetUser({});
    } catch (error) {
      console.error('getMe failed:', error);
      return null;
    }
  }

  /**
   * Update current user
   */
  async function updateUser(values: Record<string, any> = {}) {
    const password = values.password ?? null;
    const cleaned = omit(values, 'password');
    const updateMask = makeUpdateMask(Object.keys(cleaned ?? []));
    return await userProfileService.UpdateUser({
      // @ts-ignore The code generated from proto has an error.
      data: {
        ...cleaned,
      },
      password,
      // @ts-ignore The code generated from proto has an error.
      updateMask,
    });
  }

  /**
   * Change User Password
   * @param oldPassword User Old Password
   * @param newPassword User New Password
   */
  async function changePassword(oldPassword: string, newPassword: string) {
    return await userProfileService.ChangePassword({
      oldPassword,
      newPassword,
    });
  }

  /**
   * Upload user avatar (Base64)
   * @param imageBase64 Image Base64 string
   */
  async function uploadAvatarBase64(imageBase64: string) {
    return await userProfileService.UploadAvatar({
      imageBase64,
    });
  }

  /**
   * Upload user avatar (image URL)
   * @param imageUrl Image URL
   */
  async function uploadAvatarUrl(imageUrl: string) {
    return await userProfileService.UploadAvatar({
      imageUrl,
    });
  }

  /**
   * Delete user avatar
   */
  async function deleteAvatar() {
    return await userProfileService.DeleteAvatar({});
  }

  /**
   * Bind mobile number
   * @param phone Mobile number
   * @param code Verification code
   */
  async function bindPhone(phone: string, code: string) {
    return await userProfileService.BindContact({
      phone: { phone, code },
    });
  }

  /**
   * Bind Email
   * @param email Email
   * @param verificationCode Verification Code
   */
  async function bindEmail(email: string, verificationCode: string) {
    return await userProfileService.BindContact({
      email: { email, verificationCode },
    });
  }

  /**
   * Verify mobile number
   * @param phone Mobile number with country code
   * @param code SMS verification code
   * @param verificationId Verification code session ID generated by the server
   */
  async function verifyPhone(
    phone: string,
    code: string,
    verificationId?: string,
  ) {
    return await userProfileService.VerifyContact({
      phone: { phone, code },
      verificationId,
    });
  }

  /**
   * Verify Email
   * @param email Email Address
   * @param code Email Verification Code
   * @param verificationId Verification Code Session ID Generated by Server
   */
  async function verifyEmail(
    email: string,
    code: string,
    verificationId?: string,
  ) {
    return await userProfileService.VerifyContact({
      email: { email, code },
      verificationId,
    });
  }

  function $reset() {}

  return {
    $reset,
    getMe,
    updateUser,
    changePassword,
    uploadAvatarBase64,
    uploadAvatarUrl,
    deleteAvatar,
    bindPhone,
    bindEmail,
    verifyPhone,
    verifyEmail,
  };
});
